version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: annuaire_postgres
    environment:
      POSTGRES_USER: annuaire
      POSTGRES_PASSWORD: annuaire123
      POSTGRES_DB: annuaire_communautaire
    ports:
      - "5433:5432"
    volumes:
      - annuaire_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  annuaire_postgres_data:
